name: Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
          server-id: ghp
          settings-path: ${{ github.workspace }}

      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build
