name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build
        env:
          MAVEN_TYPE: release
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
          GH_PACKAGES_USER: ${{ secrets.GH_PACKAGES_USER }}
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Publish
        run: ./gradlew publish
        env:
          MAVEN_TYPE: release
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
          GH_PACKAGES_USER: ${{ secrets.GH_PACKAGES_USER }}
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Publish JavaDocs
        uses: jamesives/github-pages-deploy-action@v4
        with:
          git-config-name: "github-actions[bot]"
          git-config-email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit-message: "Update JavaDocs"
          folder: build/docs/javadoc/
          branch: pages
          target-folder: docs/
          clean: true